name = "OMIntegration"
uuid = "04712820-634a-46ba-9678-a866fbf20162"
authors = ["Notheryne"]
version = "0.1.0"

[compat]
julia = "1.4.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
